### ISSUE TITLE
 Unknown interaction

### ISSUE THREAD

**Issue by abdalla-3077** [RileCraft/DiscordBot-Template#66]
When I USE interaction Its Give Me This ERR  :

```js
DiscordAPIError[10062]: Unknown interaction
    at handleErrors (/home/container/node_modules/@discordjs/rest/dist/index.js:640:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async BurstHandler.runRequest (/home/container/node_modules/@discordjs/rest/dist/index.js:736:23)
    at async REST.request (/home/container/node_modules/@discordjs/rest/dist/index.js:1387:22)
    at async ChatInputCommandInteraction.reply (/home/container/node_modules/discord.js/src/structures/interfaces/InteractionResponses.js:111:5)
    at async Object.run (/home/container/Src/Interactions/SlashCommands/Global/slashCommands/Moderation 🗼/Ban.js:60:4)
    at async Object.run (/home/container/Src/Events/InteractionCreate.js:19:49) {
  requestBody: { files: [], json: { type: 4, data: [Object] } },
  rawError: { message: 'Unknown interaction', code: 10062 },
  code: 10062,
  status: 404,
  method: 'POST',
  url: 'https://discord.com/api/v10/interactions/1100492361219457095/aW50ZXJhY3Rpb246MTEwMDQ5MjM2MTIxOTQ1NzA5NTpYcE1JeVpZNERMNjdQdFJHSG95QU5YZHVGZ3F5SUpTeVVydTJYVWR1aHpoUEdwR2hTNzNUU1pORDlqN3kwY3doRDA3VHF2eVZhazY0NEo5WWxjZThpQjhCQ3ZoZ3VEZDhCM1RaU01wMTNpaGJOUTFlMlBoVmwwYlRjeHM1NXdaRA/callback'
}

```

**Comment by RileCraft** [comment]
Try running the interaction again

**Comment by cod9string** [comment]
دا تاخير البوت في الرد او الشخص الي بيستخدم الامر النت عندو ضعيف زي ما بيحصل معيا البوت بيفشخني
