### ISSUE TITLE
Error Cooldown

### ISSUE THREAD

**Issue by hocsinhgioitoan** [RileCraft/DiscordBot-Template#7]
`  if (!command.cooldown) return false;
                 ^

TypeError: Cannot read properties of undefined (reading 'cooldown')
    at module.exports (/home/runner/saitama/Root/Classes/CommandOptions/Cooldown.js:2:18)
    at module.exports (/home/runner/saitama/Root/Classes/CommandOptions/loadCommandOptions.js:5:75)
    at Object.run (/home/runner/saitama/Root/Events/InteractionCreate.js:5:37)
    at Client.<anonymous> (/home/runner/saitama/Root/Classes/Handlers/loadEvents.js:16:55)
    at Client.emit (node:events:402:35)
    at InteractionCreateAction.handle (/home/runner/saitama/node_modules/discord.js/src/client/actions/InteractionCreate.js:70:12)
    at Object.module.exports [as INTERACTION_CREATE] (/home/runner/saitama/node_modules/discord.js/src/client/websocket/handlers/INTERACTION_CREATE.js:4:36)
    at WebSocketManager.handlePacket (/home/runner/saitama/node_modules/discord.js/src/client/websocket/WebSocketManager.js:350:31)
    at WebSocketShard.onPacket (/home/runner/saitama/node_modules/discord.js/src/client/websocket/WebSocketShard.js:443:22)
    at WebSocketShard.onMessage (/home/runner/saitama/node_modules/discord.js/src/client/websocket/WebSocketShard.js:300:10)`

**Comment by RileCraft** [comment]
Try the latest update
